korteg=("Zheka","Vova","Python",132,222)
print(korteg)
print(korteg[1])
print(korteg[2])
print(korteg[-1])
print(korteg[-2])
for i in korteg:
    print(i)
print("======================")    
korteg=("Zheka","Vova","Python",132,222)
a = korteg.index("Python")
print(a)
last = korteg.index(222)
print(last)
